
sudo: required

cache:
  ccache: true


jobs:
  include:
    - name: "Linux AMD64 Build"
      arch: amd64
      os: linux
      dist: bionic
      group: travis_latest
      language: python
      python: "3.6"
      addons:
        apt:
          packages:
          - libblas-dev
          - liblapack-dev
          - bc
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - pip install jinja2
        - python tester.py testset_travis_blasfeo_double_amd64.json
        - python tester.py testset_travis_blas_double_amd64.json
        - python tester.py testset_travis_blas_single_amd64.json

    - name: "Linux ARM64 Build"
      arch: arm64
      os: linux
      dist: bionic
      group: travis_latest
      language: python
      python: "3.6"
      addons:
        apt:
          packages:
          - libblas-dev
          - liblapack-dev
          - bc
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - pip install jinja2
        - python tester.py testset_travis_blasfeo_double_arm64.json
        - python tester.py testset_travis_blas_double_arm64.json
        - python tester.py testset_travis_blas_single_arm64.json

    - name: "MacOS Build"
      if: branch = mac_build
      os: osx
      osx_image: xcode10.2
      language: shell
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - python3 -m pip install --user jinja2
        - python3 tester.py testset_travis.json

    - name: "Windows Build"
      if: branch = windows_build
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - pip install --user jinja2
        - python tester.py testset_travis.json


